# Support COVID-19 Tracker & CLI by using the funding links below
# Developed and Maintained by Wareneutron Developers

open_collective: covid19-tracker-cli
custom: ['https://wareneutron/donate']

# Your donation means a lot to me to continue the development of open source project like this.
