version: 2.1
orbs:
    node: circleci/node@5.0.2
jobs:
    build-and-test:
        docker:
            - image: 'cimg/base:stable'
        steps:
            - checkout
            - node/install:
                install-yarn: true
            - run: yarn install
            - run: yarn build
workflows:
    setup:
        jobs:
            - build-and-test
